### ISSUE TITLE
Need serious testing

### ISSUE THREAD

**Issue by croqaz** [croqaz/a-extractor#1]
The big problem at this point is that I have absolutely no warranty that a specific website is extracted correctly...

Testing strategy:

- create a script to download an article from a specific URL and save it into tests/fixtures/
- manually create an object with expected results when parsing that particular URL (eg: the title, the author, parts of the content)
- create a test to discover and run all saved URLs from tests/fixtures/

**Comment by Templum** [comment]
I have an additional idea for a test approach. You could use something like [puppeteer](https://github.com/GoogleChrome/puppeteer) or phantom js. Visit well-known websites/types (for example medium blog posts).  Use your tool and compare that the article includes the wanted test parts. When my time allows it I  will try to create some tests. As the project is useful to me.

**Comment by croqaz** [comment]
I already added tests for a few major sites.
Some help is still wanted, for the other major sites, but the core is already tested and is stable.
